// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using buscador.Data;

namespace buscador.Migrations
{
    [DbContext(typeof(ScraperDbContext))]
    [Migration("20200215170709_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("buscador.Data.Roupas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DataBusca")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(25);

                    b.Property<decimal>("Preco")
                        .HasColumnType("real");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<string>("UrlProduto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Roupas");
                });

            modelBuilder.Entity("buscador.Data.RoupasTamanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoupaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("RoupaId");

                    b.ToTable("RoupasTamanho");
                });

            modelBuilder.Entity("buscador.Data.RoupasTamanho", b =>
                {
                    b.HasOne("buscador.Data.Roupas", null)
                        .WithMany("Tamanhos")
                        .HasForeignKey("RoupaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
